# Generated by Django 3.1.7 on 2021-05-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_manager', '0009_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mobile', models.CharField(max_length=10, verbose_name='Customer Mobile Number')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_total_price', models.FloatField(default=0, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.FloatField(verbose_name='Unit Price')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_manager.product')),
            ],
        ),
    ]
