# Generated by Django 3.2.3 on 2021-06-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0009_product_price'),
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='review/photos')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('reviewed_dt', models.DateTimeField(auto_now_add=True)),
                ('review_edit_dt', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.product')),
            ],
        ),
    ]
