# Generated by Django 3.2.3 on 2021-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_edit_dt',
        ),
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.ImageField(null=True, upload_to='review/photos'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
