# Generated by Django 3.2.3 on 2021-06-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20210605_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='mind blowing', max_length=100),
            preserve_default=False,
        ),
    ]
