# Generated by Django 3.2.3 on 2021-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_onlineorder_onlineorderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
