# Generated by Django 3.2 on 2021-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_onlineorder_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorderitems',
            name='uprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
