# Generated by Django 3.2 on 2021-07-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0013_rename_product_id_onlineorderitems_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineorder',
            options={'ordering': ['-order_dt']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
