# Generated by Django 3.1.7 on 2021-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210411_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city']},
        ),
        migrations.AddField(
            model_name='city',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
