# Generated by Django 3.1.7 on 2021-04-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20210412_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
