# Generated by Django 3.1.7 on 2021-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210412_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='YES', max_length=3),
        ),
    ]
