# Generated by Django 3.1.7 on 2021-04-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_city_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='status',
            new_name='deliverable',
        ),
    ]
