# Generated by Django 3.1.7 on 2021-04-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_city_district'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city', 'district', 'pincode')},
        ),
    ]
