# Generated by Django 3.2 on 2021-05-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20210412_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('caption', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='category/')),
            ],
        ),
    ]
