# Generated by Django 3.2 on 2021-05-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('caption', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
