# Generated by Django 3.2 on 2021-05-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
