# Generated by Django 3.1.7 on 2021-05-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0011_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='staff/profile_pic/')),
                ('address', models.TextField(max_length=200, verbose_name='Address Line 1')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
    ]
