# Generated by Django 3.1.7 on 2021-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mobile',
            field=models.CharField(default=8281935649, max_length=10),
            preserve_default=False,
        ),
    ]
