# Generated by Django 3.1.7 on 2021-04-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('reorder_lvl', models.IntegerField()),
                ('unit_of_measure', models.CharField(choices=[('PACKET', 'Packet'), ('KG', 'Kg'), ('GRAM', 'Gram'), ('LITER', 'Liter'), ('ML', 'Ml')], default='PACKET', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manager.product')),
            ],
        ),
    ]
