# Generated by Django 3.1.7 on 2021-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20210410_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('PACKET', 'Packet'), ('BOTTLE', 'Bottle'), ('KG', 'Kg'), ('GRAM', 'Gram'), ('LITER', 'Liter'), ('ML', 'Ml')], default='PACKET', max_length=10),
        ),
    ]
