# Generated by Django 3.1.7 on 2021-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0007_auto_20210528_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
