# Generated by Django 3.1.7 on 2021-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0008_auto_20210528_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
