# Generated by Django 3.2 on 2021-07-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0009_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
